# Generated by Django 5.1.1 on 2024-10-14 08:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_slug_ismodelregistered'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyBought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_bought', to='store.item')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_bought', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
